[package]
name = "dofus_bot"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.27.2"
screencapturekit = "0.3.0"
pollster = "0.3.0"
image = "0.24"
chrono = "0.4"
rdev = "0.5"
rand = "0.8"
tokio = { version = "1", features = ["full"] }
core-media-rs = "0.3"
core-video-rs = "0.3"